In [1]:
from keras.datasets import mnist


Using TensorFlow backend.
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [9]:
dataset=mnist.load_data('mymnist.db')

In [3]:
len(dataset)

2

In [4]:
train , test = dataset


In [5]:
len(train)


2

In [6]:
X_train , y_train = train


In [7]:
X_train.shape


(60000, 28, 28)

In [8]:
X_test, y_test = test


In [10]:
X_test.shape


(10000, 28, 28)

In [11]:
img1 = X_train[0]


In [12]:
img1_label=y_train[0]


In [13]:
img1_label

5

In [14]:
img_label= y_train[5]


In [15]:
img1d=img1.reshape(28*28)


In [16]:
X_train_1d = X_train.reshape(-1 , 28*28)


In [17]:
X_train = X_train_1d.astype('float32')


In [31]:
from keras.utils.np_utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import RMSprop


In [32]:
y_train_cat=to_categorical(y_train)


In [33]:
y_train_cat

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [34]:
model =Sequential()


In [35]:
model.add(Dense(units=512, input_dim = 28*28, activation= 'relu'))


In [36]:
model.add(Dense(units=256, activation='relu'))


In [37]:
i=0
for i in range(i):
    model.add(Dense(units=128,activation='relu'))

In [38]:
model.add(Dense(units=10, activation='softmax'))


In [39]:
model.summary()


Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_5 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_6 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [40]:
model.compile(optimizer= RMSprop(),loss='categorical_crossentropy', metrics=['accuracy'])


In [41]:
h = model.fit(X_train, y_train_cat,epochs=8)



Epoch 1/8
60000/60000 [==============================] - 21s 352us/step - loss: 2.0921 - accuracy: 0.8825
Epoch 2/8
60000/60000 [==============================] - 21s 351us/step - loss: 0.5055 - accuracy: 0.9204
Epoch 3/8
60000/60000 [==============================] - 21s 352us/step - loss: 0.4801 - accuracy: 0.9291
Epoch 4/8
60000/60000 [==============================] - 21s 352us/step - loss: 0.4825 - accuracy: 0.9349
Epoch 5/8
60000/60000 [==============================] - 21s 352us/step - loss: 0.4641 - accuracy: 0.9348
Epoch 6/8
60000/60000 [==============================] - 21s 353us/step - loss: 0.4884 - accuracy: 0.9347
Epoch 7/8
60000/60000 [==============================] - 21s 344us/step - loss: 0.4991 - accuracy: 0.9333
Epoch 8/8
60000/60000 [==============================] - 20s 340us/step - loss: 0.5094 - accuracy: 0.9315


In [42]:
X_test_1d=X_test.reshape(-1, 28*28)


In [43]:
X_test= X_train_1d.astype('float32')


In [44]:
y_test_cat=to_categorical(y_test)


In [45]:
model.predict(X_test)


array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [46]:
y_test_cat

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [47]:
p=h.history['accuracy']


In [48]:
h.history['accuracy'][7]


0.93146664

In [59]:
with open('mytask3.txt', 'w') as f:
    f.write(str(p[7]))

In [60]:
model.save('task3model.h1')
